version: '3.8'

networks:
  webnet:

volumes:
  dbdata:
    name: fzy-db

services:

  kong:
    build:
      context: ./kong
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    networks:
      - webnet

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=master123
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    networks:
      - webnet
  redis:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass master123
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - webnet
  
  pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - webnet
    ports:
      - 3003:80
    links:
      - mariadb:mariadb